# Generated by Django 2.2 on 2019-10-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootest', '0002_heroinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
